//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follower
    {
        public int FollowingID { get; set; }
        public int FollowerID { get; set; }
        public int UserBeingFollowedID { get; set; }
        public Nullable<System.DateTime> FollowDate { get; set; }
        public string AllowFollow { get; set; }
    }
}
