//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBookmark
    {
        public int UserBookmarkID { get; set; }
        public int BookmarkID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Favorited { get; set; }
    }
}
