//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int UserSkillID { get; set; }
        public int TagID { get; set; }
        public int UserID { get; set; }
    
        public virtual UserSkill UserSkill1 { get; set; }
        public virtual UserSkill UserSkill2 { get; set; }
    }
}
